# Generated by Django 4.2.2 on 2024-07-01 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('cascod', models.AutoField(db_column='CasCod', primary_key=True, serialize=False, verbose_name='Código')),
                ('casesc', models.IntegerField(db_column='CasEsc', verbose_name='Escalera')),
                ('cascodblo', models.CharField(db_column='CasCodBlo', max_length=1, verbose_name='Bloque')),
                ('caspla', models.IntegerField(db_column='CasPla', verbose_name='Planta')),
                ('casnumpue', models.IntegerField(db_column='CasNumPue', verbose_name='Número de Puertas')),
                ('casmet', models.DecimalField(db_column='CasMet', decimal_places=0, max_digits=5, verbose_name='Metros')),
                ('casestreg', models.CharField(db_column='CasEstReg', default='A', max_length=1, verbose_name='Estado de Registro')),
            ],
            options={
                'verbose_name': 'Casa',
                'verbose_name_plural': 'Casas',
                'db_table': 'casa',
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('famcod', models.AutoField(db_column='FamCod', primary_key=True, serialize=False, verbose_name='Código')),
                ('famnom', models.CharField(db_column='FamNom', max_length=15, verbose_name='Nombre')),
                ('famnumint', models.IntegerField(db_column='FamNumInt', verbose_name='Número de Integrantes')),
                ('famestreg', models.CharField(db_column='FamEstReg', default='A', max_length=1, verbose_name='Estado de Registro')),
            ],
            options={
                'verbose_name': 'Familia',
                'verbose_name_plural': 'Familias',
                'db_table': 'familia',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('muncod', models.AutoField(db_column='MunCod', primary_key=True, serialize=False, verbose_name='Código')),
                ('munnom', models.CharField(db_column='MunNom', max_length=20, verbose_name='Nombre')),
                ('munpreanu', models.DecimalField(db_column='MunPreAnu', decimal_places=0, max_digits=8, verbose_name='Presupuesto Anual')),
                ('munnumviv', models.IntegerField(db_column='MunNumViv', verbose_name='Número de Viviendas')),
                ('munestreg', models.CharField(db_column='MunEstReg', default='A', max_length=1, verbose_name='Estado de Registro')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'municipio',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('percod', models.AutoField(db_column='PerCod', primary_key=True, serialize=False, verbose_name='Código')),
                ('pernom', models.CharField(db_column='PerNom', max_length=15, verbose_name='Nombre')),
                ('perapepat', models.CharField(db_column='PerApePat', max_length=10, verbose_name='Apellido Paterno')),
                ('perapemat', models.CharField(db_column='PerApeMat', max_length=10, verbose_name='Apellido Materno')),
                ('perestreg', models.CharField(db_column='PerEstReg', default='A', editable=False, max_length=1, verbose_name='Estado de Registro')),
                ('famcod', models.ForeignKey(db_column='FamCod', on_delete=django.db.models.deletion.CASCADE, to='catastroMunicipal.familia', verbose_name='Código de Familia')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('regcod', models.AutoField(db_column='RegCod', primary_key=True, serialize=False, verbose_name='Código')),
                ('regnom', models.CharField(db_column='RegNom', max_length=20, verbose_name='Nombre')),
                ('regestreg', models.CharField(db_column='RegEstReg', default='A', max_length=1, verbose_name='Estado de Registro')),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('tippercod', models.AutoField(db_column='TipPerCod', primary_key=True, serialize=False, verbose_name='Código')),
                ('tipperdes', models.CharField(db_column='TipPerDes', max_length=15, verbose_name='Descripción')),
                ('tipvivestreg', models.CharField(db_column='TipVivEstReg', max_length=1, verbose_name='Estado de Registro')),
            ],
            options={
                'verbose_name': 'Tipo de Persona',
                'verbose_name_plural': 'Tipos de Persona',
                'db_table': 'tipo_persona',
            },
        ),
        migrations.CreateModel(
            name='TipoVivienda',
            fields=[
                ('tipvivcod', models.AutoField(db_column='TipVivCod', primary_key=True, serialize=False, verbose_name='Código')),
                ('tipvivdes', models.CharField(db_column='TipVivDes', max_length=15, verbose_name='Descripción')),
                ('tipvivestreg', models.CharField(db_column='TipVivEstReg', default='A', max_length=1, verbose_name='Estado de Registro')),
            ],
            options={
                'verbose_name': 'Tipo de Vivienda',
                'verbose_name_plural': 'Tipos de Vivienda',
                'db_table': 'tipo_vivienda',
            },
        ),
        migrations.CreateModel(
            name='ZonaUrbana',
            fields=[
                ('zoncod', models.AutoField(db_column='ZonCod', primary_key=True, serialize=False, verbose_name='Código')),
                ('zonnom', models.CharField(db_column='ZonNom', max_length=20, verbose_name='Nombre')),
                ('zonestreg', models.CharField(db_column='ZonEstReg', default='A', max_length=1, verbose_name='Estado de Registro')),
                ('muncod', models.ForeignKey(db_column='MunCod', on_delete=django.db.models.deletion.CASCADE, to='catastroMunicipal.municipio', verbose_name='Código de Municipio')),
            ],
            options={
                'verbose_name': 'Zona Urbana',
                'verbose_name_plural': 'Zonas Urbanas',
                'db_table': 'zona_urbana',
            },
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('vivcod', models.AutoField(db_column='VivCod', primary_key=True, serialize=False, verbose_name='Código')),
                ('vivcal', models.CharField(db_column='VivCal', max_length=3, verbose_name='Calle')),
                ('vivnum', models.IntegerField(db_column='VivNum', verbose_name='Número')),
                ('vivcodpos', models.IntegerField(db_column='VivCodPos', verbose_name='Código Postal')),
                ('vivmet', models.DecimalField(db_column='VivMet', decimal_places=0, max_digits=4, verbose_name='Metros')),
                ('vivocu', models.CharField(db_column='VivOcu', max_length=1, verbose_name='Ocupación')),
                ('vivestreg', models.CharField(db_column='VivEstReg', default='A', max_length=1, verbose_name='Estado de Registro')),
                ('tipvivcod', models.ForeignKey(db_column='TipVivCod', on_delete=django.db.models.deletion.CASCADE, to='catastroMunicipal.tipovivienda', verbose_name='Código de Tipo de Vivienda')),
                ('zoncod', models.ForeignKey(db_column='ZonCod', on_delete=django.db.models.deletion.CASCADE, to='catastroMunicipal.zonaurbana', verbose_name='Código de Zona')),
            ],
            options={
                'verbose_name': 'Vivienda',
                'verbose_name_plural': 'Viviendas',
                'db_table': 'vivienda',
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('procod', models.AutoField(db_column='ProCod', primary_key=True, serialize=False, verbose_name='Código')),
                ('propagtri', models.DecimalField(db_column='ProPagTri', decimal_places=0, max_digits=8, verbose_name='Pago Tributario')),
                ('promoningfam', models.DecimalField(db_column='ProMonIngFam', decimal_places=0, max_digits=8, verbose_name='Ingresos Familiares')),
                ('proestreg', models.CharField(db_column='ProEstReg', default='A', editable=False, max_length=1, verbose_name='Estado de Registro')),
                ('famcod', models.ForeignKey(db_column='FamCod', on_delete=django.db.models.deletion.CASCADE, to='catastroMunicipal.familia', verbose_name='Código de Familia')),
                ('percod', models.ForeignKey(db_column='PerCod', on_delete=django.db.models.deletion.CASCADE, to='catastroMunicipal.persona', verbose_name='Código de Persona')),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietarios',
                'db_table': 'propietario',
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='tippercod',
            field=models.ForeignKey(db_column='TipPerCod', on_delete=django.db.models.deletion.CASCADE, to='catastroMunicipal.tipopersona', verbose_name='Código de Tipo de Persona'),
        ),
        migrations.CreateModel(
            name='PagoTributario',
            fields=[
                ('pagtricod', models.AutoField(db_column='PagTriCod', primary_key=True, serialize=False, verbose_name='Código')),
                ('pagtrifec', models.DateField(db_column='PagTriFec', verbose_name='Fecha')),
                ('pagtriestreg', models.CharField(db_column='PagTriEstReg', default='A', max_length=1, verbose_name='Estado de Registro')),
                ('cascod', models.ForeignKey(db_column='CasCod', on_delete=django.db.models.deletion.CASCADE, to='catastroMunicipal.casa', verbose_name='Código de Casa')),
            ],
            options={
                'verbose_name': 'Pago Tributario',
                'verbose_name_plural': 'Pagos Tributarios',
                'db_table': 'pago_tributario',
            },
        ),
        migrations.AddField(
            model_name='municipio',
            name='regcod',
            field=models.ForeignKey(db_column='RegCod', on_delete=django.db.models.deletion.CASCADE, to='catastroMunicipal.region', verbose_name='Código de Región'),
        ),
        migrations.AddField(
            model_name='casa',
            name='famcod',
            field=models.ForeignKey(db_column='FamCod', on_delete=django.db.models.deletion.CASCADE, to='catastroMunicipal.familia', verbose_name='Código de Familia'),
        ),
        migrations.AddField(
            model_name='casa',
            name='vivcod',
            field=models.ForeignKey(db_column='VivCod', on_delete=django.db.models.deletion.CASCADE, to='catastroMunicipal.vivienda', verbose_name='Código de Vivienda'),
        ),
    ]
