# Generated by Django 4.2.3 on 2024-07-15 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastroMunicipal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='CasOcu',
            field=models.CharField(choices=[('S', 'Sí'), ('N', 'No')], db_column='CasOcu', default='N', max_length=1, verbose_name='¿Está ocupada?'),
        ),
    ]
