# Generated by Django 4.2.3 on 2024-07-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastroMunicipal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vivienda',
            name='VivOcu',
        ),
        migrations.AlterField(
            model_name='familia',
            name='FamNumInt',
            field=models.IntegerField(db_column='FamNumInt', default=1, verbose_name='Número de Integrantes'),
        ),
    ]
