# Generated by Django 4.2.2 on 2024-07-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastroMunicipal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='casocu',
            field=models.CharField(choices=[('S', 'Sí'), ('N', 'No')], db_column='CasOcu', default='N', max_length=1, verbose_name='¿Está ocupada?'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='cascodblo',
            field=models.CharField(blank=True, db_column='CasCodBlo', max_length=1, null=True, verbose_name='Bloque'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='casesc',
            field=models.IntegerField(blank=True, db_column='CasEsc', null=True, verbose_name='Escalera'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='casnumpue',
            field=models.IntegerField(blank=True, db_column='CasNumPue', null=True, verbose_name='Número de Puertas'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='caspla',
            field=models.IntegerField(blank=True, db_column='CasPla', null=True, verbose_name='Planta'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='proestreg',
            field=models.CharField(db_column='ProEstReg', default='A', max_length=1, verbose_name='Estado de Registro'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='propagtri',
            field=models.DecimalField(db_column='ProPagTri', decimal_places=0, editable=False, max_digits=8, verbose_name='Pago Tributario'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='vivocu',
            field=models.CharField(choices=[('S', 'Sí'), ('N', 'No')], db_column='VivOcu', default='N', max_length=1, verbose_name='Ocupada'),
        ),
        migrations.AlterUniqueTogether(
            name='vivienda',
            unique_together={('vivcal', 'vivnum', 'vivcodpos')},
        ),
        migrations.RemoveField(
            model_name='vivienda',
            name='vivmet',
        ),
    ]
