# Generated by Django 4.2.3 on 2024-07-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastroMunicipal', '0002_remove_vivienda_vivocu_alter_familia_famnumint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='FamNumInt',
            field=models.IntegerField(db_column='FamNumInt', null=True, verbose_name='Número de Integrantes'),
        ),
    ]
