# Generated by Django 4.2.2 on 2024-07-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastroMunicipal', '0002_casa_casocu_alter_casa_cascodblo_alter_casa_casesc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='casmet',
            field=models.DecimalField(blank=True, db_column='CasMet', decimal_places=0, max_digits=5, null=True, verbose_name='Metros'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='casnumpue',
            field=models.IntegerField(blank=True, db_column='CasNumPue', null=True, verbose_name='Número de Puerta'),
        ),
    ]
