# Generated by Django 4.2.3 on 2024-07-15 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catastroMunicipal', '0002_casa_casocu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vivienda',
            name='VivOcu',
        ),
    ]
