# Generated by Django 4.2.3 on 2024-07-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastroMunicipal', '0003_remove_vivienda_vivocu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='FamNumInt',
            field=models.IntegerField(db_column='FamNumInt', default=1, verbose_name='Número de Integrantes'),
        ),
    ]
