# Generated by Django 4.2.2 on 2024-07-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastroMunicipal', '0003_alter_casa_casmet_alter_casa_casnumpue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='perestreg',
            field=models.CharField(db_column='PerEstReg', default='A', max_length=1, verbose_name='Estado de Registro'),
        ),
    ]
