# Generated by Django 5.0.6 on 2024-07-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastroMunicipal', '0004_alter_persona_perestreg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='casmet',
            field=models.DecimalField(blank=True, db_column='CasMet', decimal_places=0, default=1, max_digits=5, verbose_name='Metros'),
            preserve_default=False,
        ),
    ]
