# Generated by Django 5.0.6 on 2024-07-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastroMunicipal', '0005_alter_casa_casmet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='propagtri',
            field=models.DecimalField(db_column='ProPagTri', decimal_places=2, editable=False, max_digits=8, verbose_name='Pago Tributario'),
        ),
    ]
