from django.urls import path
from . import views

urlpatterns = [
    path('', views.main, name='main'),
    path('regiones/', views.region_list, name='region_list'),
    path('municipios/', views.municipio_list, name='municipio_list'),
    path('zonas_urbanas/', views.zona_urbana_list, name='zona_urbana_list'),
    path('tipos_vivienda/', views.tipo_vivienda_list, name='tipo_vivienda_list'),
    path('viviendas/', views.vivienda_list, name='vivienda_list'),
    path('casas/', views.casa_list, name='casa_list'),
    path('familias/', views.familia_list, name='familia_list'),
    path('personas/', views.persona_list, name='persona_list'),
    path('tipo_persona/', views.tipo_persona_list, name='tipo_persona_list'),
    path('propietarios/', views.propietario_list, name='propietario_list'),
    path('pagos_tributarios/', views.pago_tributario_list, name='pago_tributario_list'),
    path('regiones/new/', views.region_create, name='region_create'),
    path('regiones/edit/<int:pk>/', views.region_update, name='region_update'),
    path('regiones/delete/<int:pk>/', views.region_delete, name='region_delete'),
    path('municipios/new/', views.municipio_create, name='municipio_create'),
    path('municipios/edit/<int:pk>/', views.municipio_update, name='municipio_update'),
    path('municipios/delete/<int:pk>/', views.municipio_delete, name='municipio_delete'),
    path('zonas_urbanas/new/', views.zona_urbana_create, name='zona_urbana_create'),
    path('zonas_urbanas/edit/<int:pk>/', views.zona_urbana_update, name='zona_urbana_update'),
    path('zonas_urbanas/delete/<int:pk>/', views.zona_urbana_delete, name='zona_urbana_delete'),
    # path('tipos_vivienda/new/', views.tipo_vivienda_create, name='tipo_vivienda_create'),
    # path('viviendas/new/', views.vivienda_create, name='vivienda_create'),
    # path('casas/new/', views.casa_create, name='casa_create'),
    # path('familias/new/', views.familia_create, name='familia_create'),
    # path('personas/new/', views.persona_create, name='persona_create'),
    # path('tipo_persona/new/', views.tipo_persona_create, name='tipo_persona_create'),
    # path('propietarios/new/', views.propietario_create, name='propietario_create'),
    # path('pagos_tributarios/new/', views.pago_tributario_create, name='pago_tributario_create'),
    path('', views.base, name='base'),
]