# Generated by Django 4.2.2 on 2024-06-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtroModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo1', models.CharField(max_length=100)),
                ('campo2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ZonaUrbana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codzona', models.CharField(max_length=50, unique=True)),
                ('nomzona', models.CharField(max_length=100)),
                ('estado_registro', models.CharField(default='Activo', max_length=10)),
            ],
        ),
    ]
