# Generated by Django 4.2.2 on 2024-06-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastro_municipal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonaurbana',
            name='estado_registro',
        ),
        migrations.AlterField(
            model_name='otromodelo',
            name='campo2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='zonaurbana',
            name='codzona',
            field=models.CharField(max_length=10),
        ),
    ]
